version: '3'
services:
  ecomm:
    image: muralialakuntla3/ecomm
    container_name: ecomm        
    ports:
      - "8080:80"
    volumes:
      - ecomm:/usr/local/apache2/htdocs

    networks:
      - myapp
  food:
    image: muralialakuntla3/food-app   
    container_name: food
    ports:
      - "9090:80"
    volumes:
      - food:/usr/local/apache2/htdocs 

    networks:
      - myapp
networks:
  myapp:
volumes:
  ecomm:
  food:
